"""
Django settings for MyApp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Setup environment variables
env = config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='unsafe-local-secret')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='to-do-application.up.railway.app,localhost,127.0.0.1', cast=Csv())

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS', default='https://to-do-application.up.railway.app', cast=Csv())

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Production / Railway Postgres only
# DATABASE_URL must be set in the environment.
try:
    import dj_database_url
    import re

    # Use config() which automatically looks for DATABASE_URL and parses it correctly
    database_url = env('DATABASE_URL', default='')
    
    # If the URL is duplicated (contains 'postgresql://' twice), take only the first one
    if 'postgresql://' in database_url:
        parts = database_url.split('postgresql://')
        # Ensure we don't pick an empty part or a leading prefix
        for part in parts:
            if part.strip():
                # Remove any trailing 'railway' prefix if it exists from a previous concatenation
                clean_part = part.strip()
                if clean_part.endswith('railway'):
                    # Some duplications look like .../railwaypostgresql://...
                    # We want to stop at the first /railway
                    pass 
                database_url = 'postgresql://' + clean_part
                break

    # Final cleanup: ensure it doesn't have multiple URLs
    if 'postgresql://' in database_url:
        # If it still has it (e.g. data1/railwaypostgresql://data2)
        database_url = database_url.split('postgresql://')[0] + 'postgresql://' + database_url.split('postgresql://')[1]
        # Then remove anything after the first valid database name if possible?
        # A standard URL ends with /dbname. We can split by / and take parts.
        # But let's keep it simple: take only up to the first instance of a second protocol
        if 'postgresql://' in database_url[13:]: # skip the first one
             database_url = database_url[:database_url.find('postgresql://', 13)]
             # If it ends with 'railway', that was the first DB name
             if database_url.endswith('railway'):
                 pass

    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            ssl_require=True
        )
    }
    
    # Final safeguard: If the parsed name is still the whole URL (too long), force it to 'railway'
    if DATABASES['default'].get('NAME') and len(DATABASES['default']['NAME']) > 63:
        DATABASES['default']['NAME'] = 'railway'
    if not DATABASES['default']:
        raise RuntimeError('DATABASE_URL is not set; production PostgreSQL is required.')
except ImportError as exc:
    raise RuntimeError('dj_database_url must be installed to parse DATABASE_URL: %s' % exc)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


